#include "Server.h"
#include "../Log.h"
#include "RakPeerInterface.h"


int main() {
	SERVER::Server server;
	return 0;
}

namespace SERVER {


Server::Server() {
	FILE_LOG(logDEBUG) << "test";
}

void Server::tick()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000B9D begin
{
}
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000B9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace SERVER */
