#include "Player.h"




void Player::respawn()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000B3A begin
{
}
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000B3A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Player::checkIntersection()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000B4A begin
{
}
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000B4A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Player::newOperation()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000B4C begin
{
}
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000B4C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
