#include "World.h"




void World::tick()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000AD2 begin
{
}
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000AD2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void World::restartWorld()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000B35 begin
{
}
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000B35 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void World::setMap(std::string mapName)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000B37 begin
{
}
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000B37 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
