#include "viewHandler.h"

namespace CLIENT {




void viewHandler::loadResources()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000B9B begin
{
}
// section -64--88-0-108-2d44545c:13c9bbd7598:-8000:0000000000000B9B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace CLIENT */
